FROM node:22-alpine

WORKDIR /app

COPY apps/superchef/package.json apps/superchef/package.json
COPY apps/superchef/prisma/apps/superchef/schema.prisma apps/superchef/prisma/apps/superchef/schema.prisma
COPY apps/superchef/src apps/superchef/src

